#library(ggtree)
#library(treeio)
#library(phangorn)
#library(MEDICCquant)


#' plotCNAtree
#'
#' plot phylogenetic trees of CNAs. The CNAs trees were constructed by MEDICC.
#'
#' @param dist: dist files that generated by MEDICC.
#' @param bootstrap.rep.num: number of bootstrap steps.
#' @param grp: a list that used to indicate the samples groups
#' @param title: title of the plot.
#'
#'
#' @examples
#'
#' #This dist file is the output of MEDICC
#' dist = system.file(package="MPTevol", "extdata", "tree_final.dist")
#'
#' #plot CNA trees without colored samples.
#' plotCNAtree(dist = dist)
#'
#' #create a list to indicate the sample groups.
#' grp <- list(NORMAL = "NORMAL",
#'     Breast =  paste0("Breast_", 1:5),
#'     Coad = paste0("Coad_", 1:5),
#'     Lung  = paste0("Lung_", 1:5),
#'     OveryLM = paste0("OveryLM_", 1:5),
#'     OveryRM = paste0("OveryRM_", 1:6),
#'     UterusM = paste0("UterusM_", c(1:7))
#' )
#'
#' plotCNAtree(dist = dist, grp = grp)
#'
#'
#' @import ggtree
#' @import treeio
#' @import phangorn
#' @import MEDICCquant

#' @export



plotCNAtree = function(dist,
                       bootstrap.rep.num = 1000,
                       grp = NULL,
                       title = "Cancer"
                       ){

  # set certain colors
  colorScale <- c("#3C5488FF", "#00A087FF", "#F39B7fFF",
                  "#8491B4FF","#E64B35FF","#4DBBD5FF",
                  "#E41A1C", "#377EB8", "#7F0000",
                  "#35978f", "#FC8D62", "#2166ac",
                  "#E78AC3", "#A6D854", "#FFD92F",
                  "#E5C494", "#8DD3C7", "#6E016B" ,
                  "#BEBADA", "#e08214", "#80B1D3",
                  "#d6604d", "#ffff99", "#FCCDE5",
                  "#FF6A5A", "#BC80BD", "#CCEBC5" ,
                  "#fb9a99", "#B6646A", "#9F994E",
                  "#7570B3" , "#c51b7d" ,"#66A61E" ,
                  "#E6AB02" , "#003c30", "#666666")


  message("Calculate the bootstraps")


  #get trees and using NJ to get the bootstraps.
  phyloTree = bootstrap.trees(
    dist = dist,
    title = title,
    bootstrap.rep.num = bootstrap.rep.num
  )

  mtree = phyloTree$tree
  bootstrap.value = phyloTree$bootstrap.value

  #combined bootstrap
  bp2 <- data.frame(node=1:(Nnode(mtree)-1) + Ntip(mtree),
                    bootstrap = bootstrap.value  )
  mtree <- dplyr::full_join(mtree, bp2, by="node")


  p_trees <- ggtree(mtree, size=1) +
    geom_tiplab(size=4) +
    geom_treescale(fontsize=6, linesize=1, offset=1)

 p_trees = p_trees +
   geom_nodepoint(aes(fill=cut(bootstrap, c(0, 70, 90, 100))),
                  shape=21, size=2.5)+
   geom_nodepoint(aes(fill=cut(bootstrap, c(0, 70, 90, 100))),
                  shape=21, size=2.5) +
   scale_fill_manual(values=c("black", "grey", "white"),guide="legend",
                     name="Bootstrap Percentage(BP)",
                     breaks=c("(90,100]", "(70,90]", "(0,70]"),
                     labels=expression(BP>=90,70 <= BP * " < 90", BP < 70)) +
   theme_tree(legend.position=c(0.8, 0.25))

 if(!is.null(grp)){

   #check samples ids between trees and grp
   if( !identical(sort(purrr::reduce(grp, c)), sort( mtree@phylo$tip.label) ) ){
      stop("the samplenames in grp were not identical to sample names in the tree")
   }

   p_trees = groupOTU(p_trees, grp, 'Sites') + aes(color=Sites)+
     scale_colour_manual(
       values  = colorScale[29:36]
     )
 }


 p_trees + labs(title = title) +
   theme(plot.title = element_text(hjust = 0.5))

}



########################################################################################

#functions to get the bootstrap values.

medicc.resample.distance.matrices = function(D, niter=100) {
  result = list()
  pb=txtProgressBar(min=0,max=niter,style=3)
  for (s in 1:niter) {
    setTxtProgressBar(pb,s)
    Dnew = as.matrix(D)
    for (i in 1:nrow(Dnew)) {
      for (j in 1:i) {
        Dnew[i,j] = rnorm(1, mean=Dnew[i,j], sd=sqrt(Dnew[i,j]))
        Dnew[j,i] = Dnew[i,j]
      }
    }
    Dnew[Dnew<0]=0
    Dnew=round(Dnew)
    Dnew = as.dist(Dnew)
    result[[s]] = Dnew
  }
  return(result)
}


bootstrap.trees = function(dist, bootstrap.rep.num = 1000, title = "Cancer"){

  #using NJ to create a new tree with bootstrap values.
  getTrees = function(D){
    matTree <- nj(D)
    root_num <- which(matTree$tip.label == "diploid")
    matTree <- root(matTree, root_num)
    matTree
  }

  D = medicc.read.distance.matrix(dist)
  colnames(D) =rownames(D)


  matTree = getTrees(D)
  #plot(matTree)
  #bootstrap
  #resampled trees.
  resampled = medicc.resample.distance.matrices(D, bootstrap.rep.num)

  bootstrap.value = prop.clades(matTree,  lapply(resampled, getTrees) , rooted = is.rooted(matTree))/bootstrap.rep.num*100

  #bootstrap.value <- ape::boot.phylo(matTree, mut_dat, function(e){nj(dist.gene(e))},B = bootstrap.rep.num,quiet = TRUE,rooted = TRUE)/(bootstrap.rep.num)*100

  #plot( matTree, main = title)
  #nodelabels(bootstrap.value)

  #for MesKit to plot trees.
  matTree$tip.label[which( matTree$tip.label == "diploid") ] = "NORMAL"

  phyloTree = list(
    tree = matTree,
    bootstrap.value = bootstrap.value[1:(length(bootstrap.value)-1)],
    patientID = title
  )

  phyloTree

}









